### ISSUE TITLE
Imprimir esqueleto do CheckList - Time A

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#176]
# Descrição:

Essa issue tem como objetivo codificar e imprimir o CheckList presente na tela de preenchimento da avaliação. Será feito o esqueleto da tabela com os itens de checklist e, se possível, nessa sprint carregar as informações do banco de dados para essa tabela. Não é necessário cadastrar nessa issue.

# Pré-requisitos:

- [x] #147

# Tarefas:

- [x] Codificar e imprimir esqueleto do CheckList 
- [ ] Carregar informações do banco de dados para o CheckList (Opcional)

# Critério de aceitação:

- [x] Commit com os códigos do que foi solicitado
- [x] Atender padrão decidido para todos os códigos

**Comment by victordscabral** [comment]
Tarefas realizada e referenciada na issue #175 e merge #181. Commit e merge feitos. Issue finalizada.
