### ISSUE TITLE
Elaboração do RoadMap (Segunda reunião) - Geral

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#72]
# Descrição:

Realizar segunda reunião para continuação do texto do RoadMap, finalizando Features e UserStories (US) que irão compor o documento.

# Pré-requisitos:

- [x]  #19
- [x]  #22  
- [x]  #20 

# Tarefas:

- [x] Realizar segunda reunião para continuação do texto do RoadMap
- [x] Finalizar texto do RoadMap

# Critério de aceitação:

- [x] Segunda reunião realizada 
- [x] Texto do RoadMap finalizado

**Comment by SwampTG** [comment]
Sugestão, caso @victordscabral já não tenha definido totalmente um modelo, editar diretamente o roadmap do zenhub para ser mais rápido, no dia da reunião e ter o resultado no dia.

**Comment by victordscabral** [comment]
@SwampTG Eu havia feito um novo modelo para o RoadMap, mas acredito que no ZenHub a edição realmente seria mais dinâmica. Podemos então utilizar o ZenHub para preenchimento e quando uma versão capaz de atender a Release 1 estiver pronta, migrar para o novo modelo.

**Comment by victordscabral** [comment]
Texto do RoadMap entregue e seguindo para finalização (#105). Issue finalizada.
