### ISSUE TITLE
Crud da classe: Preenchimento de CheckList - Time A

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#94]
# Descrição:

Essa issue tem como objetivo a elaboração do crud para a classe Preenchimento de CheckList, parte atribuída ao Time A. O desenvolvimento será pareado entre os integrantes do time após os Dojos de treinamento, sendo a issue continuada na Sprint 06 caso não seja finalizada no período da Sprint 05.

# Pré-requisitos:

- [x] #75
- [x] #76

# Tarefas:

- [x] Conversa para pareamento entre o Time A
- [x] Elaboração do crud para a classe Preenchimento de CheckList

# Critério de aceitação:

- [x] Commit com o crud inicial para a classe Preenchimento de CheckList gerado

**Comment by victordscabral** [comment]
Crud inicial feito. Commit gerado. Issue finalizada.
