### ISSUE TITLE
Crud da classe: CheckList - Time A

### ISSUE THREAD

**Issue by victordscabral** [fga-eps-mds/2021-1-hospitalar#96]
# Descrição:

Essa issue tem como objetivo a elaboração do crud para a classe CheckList, parte atribuída ao Time A. O desenvolvimento será pareado entre os integrantes do time após os Dojos de treinamento, sendo a issue continuada na Sprint 06 caso não seja finalizada no período da Sprint 05.

# Pré-requisitos:

- [ ] #74 
- [x] #75
- [x] #76

# Tarefas:

- [ ] Conversa para pareamento entre o Time A
- [ ] Elaboração do crud para a classe CheckList

# Critério de aceitação:

- [ ] Commit com o crud para a classe Item do CheckList gerado

**Comment by victordscabral** [comment]
Crud inicial feito. Commit gerado. Issue finalizada.
